# Maintainer: Deeptadeep Roy <deeptadeeproy>
pkgname=casca
pkgver=1.0.1
pkgrel=1
pkgdesc="A btop-style concurrent multi-channel system updater utilizing a full-screen curses TUI dashboard."
arch=('any')
url="https://github.com/deeptadeeproy/casca_script"
license=('MIT')
depends=('python')

# Point source to the exact v1.0.0-arch tagged release asset
source=("${pkgname}-${pkgver}-arch.tar.gz::https://github.com/deeptadeeproy/casca_script/archive/refs/tags/v${pkgver}-arch.tar.gz")
sha256sums=('GENERATED_HASH_GOES_HERE')

package() {
    # Enter the extracted tarball directory generated by GitHub's tag layout
    cd "${srcdir}/casca_script-${pkgver}-arch"

    # Install the main execution script directly to /usr/bin/casca
    install -Dm755 casca "${pkgdir}/usr/bin/casca"
}