# Maintainer: Deeptadeep Roy <deeptadeeproy>
pkgname=casca
pkgver=1.0.3
pkgrel=1
pkgdesc="A btop-style concurrent multi-channel system updater utilizing a full-screen curses TUI dashboard."
arch=('any')
url="https://github.com/deeptadeeproy/casca_script"
license=('MIT')
depends=('python')

# Updated source target to track the exact v1.0.2-noarch tag configuration layout
source=("${pkgname}-${pkgver}-noarch.tar.gz::https://github.com/deeptadeeproy/casca_script/archive/refs/tags/v${pkgver}-noarch.tar.gz")
sha256sums=('SKIP') # Run 'updpkgsums' locally to automatically calculate and inject the exact checksum asset

package() {
    # Enter the extracted tarball directory generated by the new GitHub tag template
    cd "${srcdir}/casca_script-${pkgver}-noarch"

    # Install the main execution script directly to /usr/bin/casca
    install -Dm755 casca "${pkgdir}/usr/bin/casca"
    
    # Install the license file cleanly
    install -Dm644 LICENSE "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
}
